# Generated by Django 5.1.7 on 2025-03-17 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('rating', models.FloatField()),
                ('image', models.ImageField(upload_to='movies/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='movies/videos/')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('is_vip', models.BooleanField(default=False)),
                ('duration', models.PositiveIntegerField(default=0, help_text='المدة بالدقائق')),
                ('quality', models.CharField(choices=[('HD', 'جودة عالية'), ('FHD', 'جودة فائقة'), ('4K', 'جودة 4K')], default='HD', max_length=3)),
                ('subtitles', models.FileField(blank=True, upload_to='movies/subtitles/')),
            ],
        ),
        migrations.CreateModel(
            name='Episode_kids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='series/episodes/')),
                ('video_url', models.URLField(blank=True, max_length=500)),
                ('release_date', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='kids.movie_kids')),
            ],
        ),
    ]
