# Generated by Django 5.1.7 on 2025-03-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
