# Generated by Django 5.1.7 on 2025-03-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_kids',
            name='category',
            field=models.CharField(choices=[('كوميدي', 'كوميدي'), ('دراما', 'دراما'), ('اكشن', 'اكشن'), ('جريمة', 'جريمة'), ('رومانسي', 'رومانسي'), ('خيال علمي', 'خيال علمي'), ('تشويق', 'تشويق')], default='كوميدي', max_length=100),
        ),
    ]
