# Generated by Django 5.1.7 on 2025-03-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_episode_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('كوميدي', 'كوميدي'), ('دراما', 'دراما'), ('اكشن', 'اكشن'), ('جريمة', 'جريمة'), ('رومانسي', 'رومانسي'), ('خيال علمي', 'خيال علمي'), ('تشويق', 'تشويق')], default='كوميدي', max_length=100),
        ),
    ]
